# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [9]:
A = np.arange(1, 16).reshape(3,5)

In [13]:
#Print information
print("Dimension (Number of Axes):", A.ndim)
print("Shape:", A.shape)
print("Size (Number of Elements):", A.size)
print("Datatype:", A.dtype)


Dimension (Number of Axes): 2
Shape: (3, 5)
Size (Number of Elements): 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [7]:
# Elementwise subtraction
subtraction = B - C
print("Elementwise Subtraction (B - C):")
print(subtraction)
print()

# Elementwise multiplication
elementwise_multiplication = B * C
print("Elementwise Multiplication (B * C):")
print(elementwise_multiplication)
print()

# Matrix multiplication
matrix_multiplication = B @ C
print("Matrix Multiplication (B @ C):")
print(matrix_multiplication)

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [15]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# Exponentiate each number elementwise (use the np.exp function).
exp_B = np.exp(B)
print("Exponentiated Matrix (np.exp(B)):")
print(exp_B)
print()

# Calculate the minimum value in the whole matrix.
min_value = np.min(B)
print("Minimum Value in the Whole Matrix:")
print(min_value)
print()

# Calculate the minimum value in each row.
min_each_row = np.min(B, axis=1)
print("Minimum Value in Each Row:")
print(min_each_row)
print()

# Calculate the minimum value in each column.
min_each_column = np.min(B, axis=0)
print("Minimum Value in Each Column:")
print(min_each_column)
print()

# Find the index of the minimum value in the whole matrix (hint: use np.argmin).
index_min_value = np.argmin(B)
print("Index of the Minimum Value in the Whole Matrix:")
print(index_min_value)
print()

# Find the index of the minimum value in each row (hint: use np.argmin).
index_min_each_row = np.argmin(B, axis=1)
print("Index of the Minimum Value in Each Row:")
print(index_min_each_row)
print()

# Calculate the sum for all elements.
sum_elements = np.sum(B)
print("Sum of All Elements:")
print(sum_elements)
print()

# Calculate the mean for each column.
mean_each_column = np.mean(B, axis=0)
print("Mean for Each Column:")
print(mean_each_column)
print()

# Calculate the median for each column.
median_each_column = np.median(B, axis=0)
print("Median for Each Column:")
print(median_each_column)

Exponentiated Matrix (np.exp(B)):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum Value in the Whole Matrix:
1

Minimum Value in Each Row:
[1 4 7]

Minimum Value in Each Column:
[1 2 3]

Index of the Minimum Value in the Whole Matrix:
0

Index of the Minimum Value in Each Row:
[0 0 0]

Sum of All Elements:
45

Mean for Each Column:
[4. 5. 6.]

Median for Each Column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [19]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [21]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
När man använder färre index än vad matrisen har axlar, betyder det att man bara anger en del av informationen.
I exemplet `A[1]` hämtar man hela den andra raden i matrisen, eftersom man bara angav radindex (1).
Om man också vill hämta en specifik kolumn i den raden, måste man lägga till kolumnindex, t.ex. `A[1, 2]`.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [25]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [27]:
# det är bättre att använda **`np.nditer`** för att enkelt iterera genom alla element i en array.
for element in np.nditer(A):
    print(element)


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [29]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
Koden skapar en array med 30 tal och omformar den till en 3D-array (en matris som har både höjd, bredd och djup) med formen (2, 3, 5).
Det betyder att arrayen har 3 axlar: 2 block, varje block har 3 rader, och varje rad har 5 tal. 
#(det finns 30 element, och de första två dimensionerna 2*3 tar 6 element,därför måste den sista dimensionen 30/6 ha 5 element)

In [31]:
# Till example :
import numpy as np
a = np.arange(12)
b = a.reshape(2, 2, 3)
print(a)
print()
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [33]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [35]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [37]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [39]:
import numpy as np

# Steg 1: Skapa en funktion
def add_mult_matrices(matrix1, matrix2, operation):
    # Kontrollera om matriserna är numpy-arrayer
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        return "Båda matriserna måste vara numpy-arrayer"
    
    # Kontrollera om operationen är giltig ('add' eller 'multiply')
    if operation not in ['add', 'multiply']:
        return "Angiv 'add' för addition eller 'multiply' för multiplikation"
    
    # Steg 2: Validera inmatningen
    if operation == 'add':
        # Kontrollera att matriserna har samma storlek
        if matrix1.shape != matrix2.shape:
            return "Matriserna måste ha samma storlek för addition"
        return matrix1 + matrix2  # Utför addition
    
    # Steg 3: Utföra operationen
    if operation == 'multiply':
        # Kontrollera att antalet kolumner i första matrisen är lika med antalet rader i andra matrisen
        if matrix1.shape[1] != matrix2.shape[0]:
            return "Antalet kolumner i första matrisen måste vara lika med antalet rader i andra matrisen"
        return np.dot(matrix1, matrix2)  # Utför matrismultiplikation med np.dot

# Steg 4: Returnera resultatet
X = np.array([[4, 7], [8, 5]])  # Matris för addition
Y = np.array([[1, 3], [2, 6]])  # Matris för addition
P = np.array([[2, 1, 3], [4, 1, 5]])  # Matris för multiplikation
Q = np.array([[1, 2], [3, 4], [5, 6]])  # Matris för multiplikation

# Steg 5: Använda funktionen
print("Addition:\n", add_mult_matrices(X, Y, 'add'))
print("Multiplikation:\n", add_mult_matrices(P, Q, 'multiply'))


Addition:
 [[ 5 10]
 [10 11]]
Multiplikation:
 [[20 26]
 [32 42]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [47]:
import numpy as np

# Definiera vektorn x
x = np.array([4, 3])

# (a) Dimensionen av vektorn x
# x är en 1D-vektor
print(f"(a) Dimensionen av x: {x.ndim}")

# (b) Beräkna 5x
# Multiplicera varje element i x med 5
print(f"(b) 5x: {5 * x}")

# (c) Beräkna 3x
# Multiplicera varje element i x med 3
print(f"(c) 3x: {3 * x}")

# (d) Beräkna 5x + 3x
# Addera 5x och 3x
print(f"(d) 5x + 3x: {5 * x + 3 * x}")

# (e) Beräkna 8x
# Multiplicera varje element i x med 8
print(f"(e) 8x: {8 * x}")

# (f) Beräkna 4x − x
# Subtrahera x från 4x
print(f"(f) 4x − x: {4 * x - x}")

# (g) Beräkna x⊤ (transponerad vektor)
# Transponeringen ändrar inte en 1D-vektor
x_transpose = x.T
print(f"(g) x⊤: {x_transpose}")
print(f"Dimensionen efter transponering: {x_transpose.ndim}")

# (h) Är x + x⊤ definierat?
# För 1D-vektorer går det inte att addera x och x⊤
try:
    result = x + x_transpose
    print(f"(h) x + x⊤: {result}")
except ValueError:
    print("(h) x + x⊤ är inte definierat")

# (i) Beräkna ∥x∥ (normen av x)
# Detta ger längden på vektorn
print(f"(i) ∥x∥: {np.linalg.norm(x)}")


(a) Dimensionen av x: 1
(b) 5x: [20 15]
(c) 3x: [12  9]
(d) 5x + 3x: [32 24]
(e) 8x: [32 24]
(f) 4x − x: [12  9]
(g) x⊤: [4 3]
Dimensionen efter transponering: 1
(h) x + x⊤: [8 6]
(i) ∥x∥: 5.0


In [49]:
import numpy as np

# Definiera vektorn v
v = np.array([3, 7, 0, 11])

# (a) Dimensionen av vektorn v
# v är en 1D-vektor med 4 element
print(f"(a) Dimensionen av v: {v.ndim}")

# (b) Beräkna 2v
# Multiplicera varje element i v med 2
print(f"(b) 2v: {2 * v}")

# (c) Beräkna 5v + 2v
# Addera 5v och 2v
print(f"(c) 5v + 2v: {5 * v + 2 * v}")

# (d) Beräkna 4v − 2v
# Subtrahera 2v från 4v
print(f"(d) 4v − 2v: {4 * v - 2 * v}")

# (e) Beräkna v⊤ (transponerad vektor)
# Transponering gör vektorn om till en kolumnvektor
v_transpose = v.T
print(f"(e) v⊤: {v_transpose}")
print(f"Dimensionen efter transponering: {v_transpose.ndim}")

# (f) Beräkna ∥v∥ (normen av v)
# Detta ger längden på vektorn
print(f"(f) ∥v∥: {np.linalg.norm(v)}")


(a) Dimensionen av v: 1
(b) 2v: [ 6 14  0 22]
(c) 5v + 2v: [21 49  0 77]
(d) 4v − 2v: [ 6 14  0 22]
(e) v⊤: [ 3  7  0 11]
Dimensionen efter transponering: 1
(f) ∥v∥: 13.379088160259652


In [51]:
import numpy as np

# Definiera vektorerna v1 och v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# (a) Beräkna ∥v1∥ (normen av v1)
norm_v1 = np.linalg.norm(v1)
print(f"(a) ∥v1∥: {norm_v1}")

# (b) Beräkna ∥v1 − v2∥ (normen av skillnaden mellan v1 och v2)
diff = v1 - v2
norm_diff = np.linalg.norm(diff)
print(f"(b) ∥v1 − v2∥: {norm_diff}")


(a) ∥v1∥: 7.14142842854285
(b) ∥v1 − v2∥: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [60]:
import numpy as np

# Definiera matriserna
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])


In [62]:
result_a = 2 * A
print(f"(a) 2A:\n{result_a}\n")


(a) 2A:
[[ 4  2 -2]
 [ 2 -2  2]]



In [64]:
result_b = B - 2 * A
print(f"(b) B - 2A:\n{result_b}\n")


(b) B - 2A:
[[ 0 -4  3]
 [ 0 -2 -4]]



In [66]:
result_c = 3 * C - 2 * E
print(f"(c) 3C - 2E:\n{result_c}\n")


(c) 3C - 2E:
[[ 1  4]
 [ 2 -1]]



In [68]:
result_d = 2 * D - 3 * C
print(f"(d) 2D - 3C:\n{result_d}\n")


(d) 2D - 3C:
[[3 2]
 [2 3]]



In [132]:
result_e = D.T + 2 * D
print(f"(e) DT + 2D:\n{result_e}\n")


(e) DT + 2D:
[[ 9 12 17]
 [12  9 20]
 [19 22 27]]



In [146]:
result_f = 2 * C.T - 2 * D.T
print(f"(f) 2C^T - 2D^T:\n{result_f}\n")


(f) 2C^T - 2D^T:
[[-4 -4]
 [-4 -4]]



In [84]:
result_g = A.T - B.T  # Använd BT istället för B ( kan subtrahera eftersom båda matriserna har samma dimensioner)
print(f"(g) AT - B:\n{result_g}\n")


(g) AT - B:
[[-2 -1]
 [ 3  3]
 [-2  3]]



In [158]:
C = np.array([[1, 2, 3], [2, 1, 4], [3, 2, 1]])  # Rätt dimension (3, 3)
result_h = np.dot(A, C)  # Multiplicera A (2, 3) med C (3, 2)
print(f"(h) AC:\n{result_h}\n")


(h) AC:
[[3.09734183 2.21984932 3.35019595]
 [2.48375344 2.73455577 5.60671134]]



In [102]:
result_i = np.dot(C, D)
print(f"(i) CD:\n{result_i}\n")


(i) CD:
[[11 10]
 [10 11]]



In [120]:
result_j = np.dot(C, B.T)  # Vi multiplicerar med B transponerad för att göra det möjligt
print(f"(j) CB:\n{result_j}\n")

(j) CB:
[[  3 -12]
 [ 10  -8]
 [  9  -4]]



In [106]:
result_k = np.dot(C, I)
print(f"(k) CI:\n{result_k}\n")


(k) CI:
[[1 2]
 [2 1]]



In [108]:
result_l = np.dot(A, B.T)
print(f"(l) AB^T:\n{result_l}\n")


(l) AB^T:
[[5 2]
 [7 4]]



In [166]:
import numpy as np

# Definiera matrisen A
A = np.array([[2, 3, 4], [5, 4, 1]])

# Multiplicera A med dess transponat (A^T)
result = np.dot(A, A.T)

# Visa resultatet
print("Resultatet av A * A^T:")
print(result)


Resultatet av A * A^T:
[[29 26]
 [26 42]]


In [162]:
import numpy as np

# Definiera matriserna A, B och C
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

# Beräkna produkterna AB och AC
AB = np.dot(A, B)
AC = np.dot(A, C)

# Visa resultaten
print("A * B:")
print(AB)

print("\nA * C:")
print(AC)

# Kontrollera om B och C är lika
if np.array_equal(B, C):
    print("\nB och C är lika.")
else:
    print("\nB och C är olika.")


A * B:
[[ 4  7]
 [ 8 14]]

A * C:
[[ 4  7]
 [ 8 14]]

B och C är olika.


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [41]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [43]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [45]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [172]:
import numpy as np

# Skapa en lista som vi kallar v1
v1 = np.arange(4)  # Det här ger oss vektorn [0, 1, 2, 3]
print("v1 innan ändring:", v1)

# Skapa en ny lista v2 som bara tar de sista två elementen från v1
v2 = v1[-2:]  # v2 blir då [2, 3] och är en kopia som refererar till samma data som v1
print("v2 innan ändring:", v2)

# Här kollar vi om v2 är en vy av v1 (dvs. de delar samma data)
if v2.base is v1:
    print("v2 är en vy av v1.")  # Om det är samma data, betyder det att v2 är en vy
else:
    print("v2 är en kopia av v1.")  # Om det inte är samma data, då är v2 en kopia

# Nu ändrar vi det sista elementet i v2 till 123
v2[-1] = 123  # Det här ändrar också det sista elementet i v1 eftersom de delar samma data
print("\nv1 efter ändring:", v1)  # Vi kollar på v1 efter att ha ändrat v2
print("v2 efter ändring:", v2)  # Och v2 efter ändringen


v1 innan ändring: [0 1 2 3]
v2 innan ändring: [2 3]
v2 är en vy av v1.

v1 efter ändring: [  0   1   2 123]
v2 efter ändring: [  2 123]
